# Generated by Django 3.2.4 on 2021-06-29 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.CharField(default=uuid.UUID('8935f7e1-88ba-498c-bf36-4ae09218e179'), max_length=100, primary_key=True, serialize=False, unique=True)),
                ('redirect', models.URLField()),
                ('hit_count', models.IntegerField()),
            ],
        ),
    ]
