# Generated by Django 3.2.4 on 2021-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20210629_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='id',
            field=models.SlugField(default='20cd4', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
